spring:
  application:
    name: openatom-system
  datasource:
    url: jdbc:mysql://localhost:3306/openatom-system?serverTimeZone=UTC
    username: ${DB_USENAME:root}
    password: ${DB_PASSWORD:ab321818}
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8921
  servlet:
    context-path: /api/v1

sa-token:
  token-name: jmiopenatom
  timeout: 2592000
  active-timeout: -1
  is-concurrent: true
  is-share: false
  token-style: uuid
  is-log: true
